const express = require('express');
const user = require('../controllers/user.controller');
const verifyToken = require('../middleware/verifytoken');
const allowedTo = require('../middleware/allowedTo');
const userRoles = require('../utilities/userRoles');
const router = express.Router();
router.get('/', verifyToken ,allowedTo(userRoles.ADMIN) , user.getAllUsers);
router.post('/register', user.register);
router.post('/login', user.login);
module.exports = router;